from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class SentimentAnalysis(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, sentiment=None):  # noqa: E501
        """SentimentAnalysis - a model defined in OpenAPI

        :param sentiment: The sentiment of this SentimentAnalysis.  # noqa: E501
        :type sentiment: str
        """
        self.openapi_types = {
            'sentiment': str
        }

        self.attribute_map = {
            'sentiment': 'sentiment'
        }

        self._sentiment = sentiment

    @classmethod
    def from_dict(cls, dikt) -> 'SentimentAnalysis':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The sentimentAnalysis of this SentimentAnalysis.  # noqa: E501
        :rtype: SentimentAnalysis
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sentiment(self) -> str:
        """Gets the sentiment of this SentimentAnalysis.


        :return: The sentiment of this SentimentAnalysis.
        :rtype: str
        """
        return self._sentiment

    @sentiment.setter
    def sentiment(self, sentiment: str):
        """Sets the sentiment of this SentimentAnalysis.


        :param sentiment: The sentiment of this SentimentAnalysis.
        :type sentiment: str
        """

        self._sentiment = sentiment
